### ISSUE TITLE
AssertionError: No data when reading ... check for sox crash at line 2488 in gradint v3.01  on Python 2.7.17

### ISSUE THREAD

**Issue by rdearman** [ssb22/gradint#1] opened 2020-02-16 21:32 UTC
I get an AssertionError when attempting to create an MP3 (or other audio file) of my lesson. My lessons are all sample files for example:
100_R006-03_en.txt  
100_R006-03_zh.mp3 
where the file ending in _zh.mp3 is the audio and _en.txt  is simply the english text. As per the instructions included in the program. I've attached the error file.
[last-gradint-error.txt](https://github.com/ssb22/gradint/files/4210947/last-gradint-error.txt)

I have also run the program with a newer version of python 3.6 and I get:
TypeError: must be str, not bytes at line

[last-gradint-error.txt](https://github.com/ssb22/gradint/files/4210949/last-gradint-error.txt)

**Comment by ssb22** [comment] 2020-02-16 23:55
Thanks.  This is probably due to some missing test coverage when I added Python 3 compatibility to the code (which was Python2-only before Gradint 3.0).  Adding Python 3 compatibility to an existing Python 2 codebase may create bugs that manifest themselves under both Python 3 AND Python 2.  So I tried to test the port as much as possible, but it's inevitable something gets missed and has to be picked up later.  For this reason I would have liked to have left my code in Python 2 permanently, if it weren't for the fact that so many GNU/Linux distributions are now completely dropping Python 2 from their latest releases.  (The way this "2 to 3" thing has been handled in general is causing a lot of breakage to a lot of people's projects, and I don't feel I really like Python anymore.)

The error under Python 3.6 can be fixed by changing the code to say `S(file)` instead of `file` (I'll do this in the next version), but the cause of the error under Python 2.7 is not so obvious: it tried to read a `wav` file it had created, only to find the `wav` file was empty.  To find the true cause of that error, we need to look further back in the terminal to see any warnings that might have been printed by `sox` when trying to speak those `txt` files.  Would you be able to run Gradint in a terminal and post the entire output (not just the error)?

**Comment by rdearman** [comment] 2020-02-17 21:51
Sure no problem. I've included all the redirected output in the "allout.txt" file and I also attached the last error file. 

[last-gradint-error.txt](https://github.com/ssb22/gradint/files/4216377/last-gradint-error.txt)

[allout.txt](https://github.com/ssb22/gradint/files/4216374/allout.txt)

**Comment by ssb22** [comment] 2020-02-17 23:09
Ah yes, the first line of `allout.txt` is saying `sox FAIL formats: no handler for given file type mp3`.  That means the `sox` program on your system did not get MP3 support compiled-in by whoever built your distro.  Some distros ship all the formats as a separate package, called something like `libsox-fmt-all`, so you could check your distro's package manager to see if there's a `libsox-fmt-all` package which will add MP3 support to your `sox`.  Alternatively, you could install `madplay` or `mpg123`.

If Gradint finds `madplay` on the system, it will use it for MP3 files, otherwise it checks for `mpg123`, and if that's missing too, it uses `sox`.  But it did not include a check to make sure the `sox` on your system actually supports MP3, which is why it crashed when it turned out your system's `sox` does not support MP3.

So the quickest way to make this problem go away is just to install `madplay` or `mpg123` or `libsox-fmt-all` on your system.

But what I will do is add some code to Gradint to check that `sox` MP3 support is there before using it, and if it's not there then print up a better error message (the existing message includes the words `"check for sox crash"` but you evidently didn't notice this, which is not your fault, it means the error message was not fit for purpose).  On Windows and Mac we bundle our own `sox` along with Gradint, so we know `sox` has all the parts we need, but on GNU/Linux we rely on whatever `sox` is there on the system, which might be missing support for some file types if `libsox-fmt-all` hasn't been installed, so we need to check more carefully.

**Comment by rdearman** [comment] 2020-02-18 22:28
Python2 version: I did install madplay, but got a lot of odd errors in the output. (Pasted below). I then installled libsox-fmt-all, same result. Installled mpg123, same result. I think it might be something to do with reading in the mp3 files which I've put into the samples directory. I copied one of them here for you. (zip file)
[1_tmp1cctcn_zh.mp3.zip](https://github.com/ssb22/gradint/files/4221969/1_tmp1cctcn_zh.mp3.zip)

Python3 version: I tried adding s(file) to line 2275 (?) but no success, there are lots of entries for "file" can you tell me which line number you had in mind?


-----   >8
sox WARN wav: Premature EOF on .wav input file
sox WARN wav: Premature EOF on .wav input file
sox WARN dither: dither clipped 252 samples; decrease volume?
sox WARN dither: dither clipped 1 samples; decrease volume?
sox WARN dither: dither clipped 246 samples; decrease volume?
sox WARN dither: dither clipped 221 samples; decrease volume?
sox WARN dither: dither clipped 1 samples; decrease volume?
sox WARN dither: dither clipped 201 samples; decrease volume?
sox WARN dither: dither clipped 223 samples; decrease volume?
sox WARN dither: dither clipped 1 samples; decrease volume?
sox WARN dither: dither clipped 235 samples; decrease volume?
sox WARN dither: dither clipped 1 samples; decrease volume?
sox WARN wav: Premature EOF on .wav input file
sox WARN wav: Premature EOF on .wav input file
WARNING: libsndfile may ignore -r and perform fseek's on the input.
Compile without libsndfile if this is a problem.
Assuming raw pcm input file : Forcing byte-swapping
LAME 3.100 64bits (http://lame.sf.net)
Resampling:  input 44.1 kHz  output 22.05 kHz
polyphase lowpass filter disabled
Encoding <stdin> to output/lesson17.mp3
Encoding as 22.05 kHz single-ch MPEG-2 Layer III VBR(q=6.47451)

**Comment by ssb22** [comment] 2020-02-18 23:05
Hi, the lines you pasted are all warnings not errors, and they are mostly sox warning us about a slight loss of sound quality, probably because the madplay volume setting is slightly too high.  You could address this by reducing `soundVolume` in `advanced.txt`, but really your ears are the best judge of whether or not it's a serious problem: if you can't hear the difference in the output lesson, then it's OK.

**Comment by rdearman** [comment] 2020-02-19 09:58
> 
> 
> Hi, the lines you pasted are all warnings not errors, and they are mostly sox warning us about a slight loss of sound quality, probably because the madplay volume setting is slightly too high. You could address this by reducing `soundVolume` in `advanced.txt`, but really your ears are the best judge of whether or not it's a serious problem: if you can't hear the difference in the output lesson, then it's OK.

Sorry, perhaps I didn't explain it well. The resulting WAV file has no audio at all. It produces a 16kb empty file. I thought perhaps the stuff I was pasting was the reason it was generating an empty audio file and would help.

**Comment by ssb22** [comment] 2020-02-19 10:39
Hi, a 16Kb empty WAV file doesn't sound right, because the output you pasted said it made an MP3 file called `output/lesson17.mp3`.  Did you try listening to `output/lesson17.mp3`, and was there sound in that?  What was the name of the 16Kb empty WAV file?  thanks.

**Comment by rdearman** [comment] 2020-02-19 13:42
I've zipped up lesson17 and one of the 16kb files. It also had lesson1.ogg & wav. So I put (hopefully) sufficient  examples in. 
[output.zip](https://github.com/ssb22/gradint/files/4225332/output.zip)

On a side note, I cloned the latest github source to try to build it myself, but the gradint.py script isn't actually in there?

**Comment by ssb22** [comment] 2020-02-19 14:16
The timestamps of those files (which you can see via `ls -l`) show that `lesson1.mp3`, `lesson1.ogg` and `lesson1.wav` were all generated on Sunday 16th February, while `lesson10.mp3` was generated on Monday 17th February and `lesson17.mp3` was generated on Tuesday 18th February.  Since you didn't install `madplay` etc until at least the 17th (if this thread is anything to go by), I suggest ignoring any old output files that were generated on or before the 17th.  (Gradint never deletes its old output files, as it assumes you might want to generate multiple lessons at once to take on a trip or something.  So if you have multiple old output files 'knocking around' then you need to clean them up yourself I'm afraid.  I was expecting most people to use Gradint "live", with creating an output file being the exception for occasional use when you need to take an MP3 file away from the computer.)

Yes it is correct that the `gradint.py` file is not in the Github source.  That's because `gradint.py` is generated automatically by combining all the other `.py` files in the `src` directory.  This happens when you type `make` at top-level (the `make` command reads `Makefile` for instructions, and the default target in that `Makefile` is to build `gradint.py` from the other `.py` files).  I prefer the files to be split up for easier editing, but I combine them for easier shipping to the various platforms (Windows, Mac, GNU/Linux, Symbian S60, Windows Mobile 6, RISC OS, Android QPython, and CGI).  Incidentally, the reason why there are so many platforms is that I've had friends who said "I **will** start my language learning after you make it compatible with X", but when I do make it compatible with X they don't start.  So now when people say "I will use it if you make the interface prettier" or whatever, I tend not to listen anymore because I've heard the words "I will use it if" too often and they tend to be mistaken.  But we might as well keep all the platforms we've got, at least for now.

**Comment by rdearman** [comment] 2020-02-19 16:11
I understand the use case, the snag is I commute a lot, so a take away file would be good for me. I removed all the old output, did a make on the new source. But the problem is the same. Just static sound. Probably something to do with my Linux install. I'll try it on a Windoze machine and see if I can get it working. Thanks for all your assistance BTW. :)

**Comment by ssb22** [comment] 2020-02-19 17:43
Ah, I managed to root-cause the static problem.

Gradint uses LAME to create MP3 files.  Unfortunately, the parameters it needs to send to LAME vary depending on which version of LAME is installed on the system.  Therefore, Gradint checks the LAME version number, and does one thing if it gets 3.97 or below, but another thing if it gets 3.98 or above.

Unfortunately, the code to do this read only the first 4 characters of the version number, so when LAME hit version 3.100, Gradint started to read this as 3.10, and incorrectly applied the "before 3.97" parameters, causing LAME to read the bytes of our samples in the wrong order, turning anything other than silence into static (but only when creating MP3 files, not when creating OGG or WAV or SPX).

I didn't notice this during testing because I had not tried version 3.100 of LAME.

**Closed as completed** 2020-02-19 17:45 UTC

**Comment by ssb22** [comment] 2020-02-19 17:47
Please try the latest version I just committed.  I tested on a Fedora 31 Linux system with LAME 3.100 installed, with both Python 2 and Python 3 and I do not get static when creating MP3 files.

**Comment by rdearman** [comment] 2020-02-19 22:01
Perfect !!! Works a treat. Thanks a lot for all your help.
